//Still Need to add Sporadic, SLayer, Minigame, Skilling, and Raid bosses
import ahrim from "/src/assets/bossImages/ahrim.png"

export const bossList = [
    {
        name: `Ahrim the Blighted`,
        level: 98,
        health: 100,
        attack: ["Magic"],
        region: "Morytania",
        release: 2005,
        hasPet: "No",
        image: ahrim,
    },
    {
        name: `Artio`,
        level: 320,
        health: 450,
        attack: ["Magic", "Melee", "Ranged"],
        region: "Wilderness",
        release: 2023,
        hasPet: "Yes",
    }, 
    {
        name: `Blood Moon`,
        level: 329,
        health: 500,
        attack: ["Melee"],
        region: "Varlamore",
        release: 2024,
        hasPet: "No",
    },
    {
        name: `Blue Moon`,
        level: 329,
        health: 500,
        attack: ["Melee"],
        region: "Varlamore",
        release: 2024,
        hasPet: "No",
    },
    {
        name: `Calisto`,
        level: 470,
        health: 1000,
        attack: ["Magic", "Melee", "Ranged"],
        region: "Wilderness",
        release: 2014,
        hasPet: "Yes",
    }, 
    {
        name: `Calvar'ion`,
        level: 264,
        health: 150,
        attack: ["Melee"],
        region: "Wilderness",
        release: 2023,
        hasPet: "Yes",
    }, 
    {
        name: `Chaos Elemental`,
        level: 305,
        health: 250,
        attack: ["Magic", "Melee", "Ranged"],
        region: "Wilderness",
        release: 2006,
        hasPet: "Yes",
    }, 
    {
        name: `Chaos Fanatic`,
        level: 202,
        health: 225,
        attack: ["Magic"],
        region: "Wilderness",
        release: 2014,
        hasPet: "Yes",
    }, 
    {
        name: "Commander Zilyana",
        level: 596,
        health: 255,
        attack: ["Magic", "Melee"],
        region: "Asgarnia",
        release: 2013,
        hasPet: "Yes",
    },
    {
        name: `Corporeal Beast`,
        level: 785,
        health: 2000,
        attack: ["Magic", "Melee"],
        region: "Wilderness",
        release: 2014,
        hasPet: "Yes",
    }, 
    {
        name: `Crazy Archaeologist`,
        level: 204,
        health: 225,
        attack: ["Melee", "Ranged"],
        region: "Wilderness",
        release: 2014,
        hasPet: "No",
    }, 
    {
        name: `Dagannoth Prime`,
        level: 303,
        health: 255,
        attack: ["Magic"],
        region: "Fremennik Province",
        release: 2005,
        hasPet: "Yes",
    },
    {
        name: `Dagannoth Rex`,
        level: 303,
        health: 255,
        attack: ["Melee"],
        region: "Fremennik Province",
        release: 2005,
        hasPet: "Yes",
    },
    {
        name: `Dagannoth Supreme`,
        level: 303,
        health: 255,
        attack: ["Ranged"],
        region: "Fremennik Province",
        release: 2005,
        hasPet: "Yes",
    },
    {
        name: `Deranged Archaeologist`,
        level: 276,
        health: 200,
        attack: ["Melee", "Ranged"],
        region: "Misthalin",
        release: 2017,
        hasPet: "No",
    },
    {
        name: `Dharok the Wretched`,
        level: 115,
        health: 100,
        attack: ["Melee"],
        region: "Morytania",
        release: 2005,
        hasPet: "No",
    }, 
    {
        name: `Duke Sucellus`,
        level: 768,
        health: 440,
        attack: ["Magic", "Melee"],
        region: "Fremennik Province",
        release: 2023,
        hasPet: "Yes",
    }, 
    {
        name: `Eclipse Moon`,
        level: 329,
        health: 500,
        attack: ["Melee"],
        region: "Varlamore",
        release: 2024,
        hasPet: "No",
    },
    {
        name: "General Graardor",
        level: 624,
        health: 255,
        attack: ["Melee","Ranged"],
        region: "Asgarnia",
        release: 2013,
        hasPet: "Yes",
    },
    {
        name: `Giant Mole`,
        level: 230,
        health: 200,
        attack: ["Melee"],
        region: "Asgarnia",
        release: 2006,
        hasPet: "Yes",
    },
    {
        name: `Guthan the Infested`,
        level: 115,
        health: 100,
        attack: ["Melee"],
        region: "Morytania",
        release: 2005,
        hasPet: "No",
    },
    {
        name: "Kalphite Queen",
        level: 333,
        health: 510,
        attack: ["Magic", "Melee", "Ranged"],
        region: "Kharidian Desert",
        release: 2004,
        hasPet: "Yes",
    }, 
    {
        name: `Karil the Tainted`,
        level: 98,
        health: 100,
        attack: ["Ranged"],
        region: "Morytania",
        release: 2005,
        hasPet: "No",
    },
    {
        name: `King Black Dragon`,
        level: 276,
        health: 240,
        attack: ["Dragonfire", "Melee"],
        region: "Wilderness",
        release: 2002,
        hasPet: "Yes",
    }, 
    {
        name: "K'ril Tsutsaroth",
        level: 650,
        health: 255,
        attack: ["Magic", "Melee"],
        region: "Asgarnia",
        release: 2013,
        hasPet: "Yes",
    },
    {
        name: "Kree'arra",
        level: 580,
        health: 255,
        attack: ["Magic", "Ranged", "Melee"],
        region: "Asgarnia",
        release: 2013,
        hasPet: "Yes",
    },
    {
        name: `The Leviathan`,
        level: 798,
        health: 900,
        attack: ["Magic", "Melee", "Ranged"],
        region: "Kharidian Desert",
        release: 2023,
        hasPet: "Yes",
    }, 
    {
        name: `Nex`,
        level: 1001,
        health: 3400,
        attack: ["Magic", "Melee", "Ranged"],
        region: "Asgarnia",
        release: 2022,
        hasPet: "Yes",
    }, 
    {
        name: `The Nightmare`,
        level: 841,
        health: 2400,
        attack: ["Magic", "Melee", "Ranged"],
        region: "Morytania",
        release: 2020,
        hasPet: "Yes",
    }, 
    {
        name: `Phantom Muspah`,
        level: 741,
        health: 850,
        attack: ["Magic", "Melee", "Ranged"],
        region: "Fremennik Province",
        release: 2023,
        hasPet: "Yes",
    }, 
    {
        name: `Phosani's Nightmare`,
        level: 1024,
        health: 3200,
        attack: ["Magic", "Melee", "Ranged"],
        region: "Morytania",
        release: 2021,
        hasPet: "Yes",
    }, 
    {
        name: `Revenant Maledictus`,
        level: 397,
        health: 1250,
        attack: ["Magic", "Ranged"],
        region: "Wilderness",
        release: 2022,
        hasPet: "No",
    }, 
    {
        name: `Sarachnis`,
        level: 318,
        health: 400,
        attack: ["Melee", "Ranged"],
        region: "Kourend",
        release: 2019,
        hasPet: "Yes",
    },
    {
        name: `Scorpia`,
        level: 225,
        health: 200,
        attack: ['Melee'],
        region: 'Wilderness',
        release: 2014,
        hasPet: "Yes",
    }, 
    {
        name: `Scurrius`,
        level: 200,
        health: 500,
        attack: ["Magic", "Melee", "Ranged"],
        region: "Misthalin",
        release: 2024,
        hasPet: "Yes",
    },
    {
        name: `Spindel`,
        level: 302,
        health: 515,
        attack: ["Magic", "Melee", "Ranged"],
        region: "Wilderness",
        release: 2023,
        hasPet: "Yes",
    }, 
    {
        name: `Torag the Corrupted`,
        level: 115,
        health: 100,
        attack: ["Melee"],
        region: "Morytania",
        release: 2005,
        hasPet: "No",
    }, 
    {
        name: `Vardorvis`,
        level: 784,
        health: 700,
        attack: ["Melee"],
        region: "Kourend",
        release: 2023,
        hasPet: "Yes",
    }, 
    {
        name: `Venenatis`,
        level: 464,
        health: 850,
        attack: ["Magic", "Melee", "Ranged"],
        region: "Wilderness",
        release: 2014,
        hasPet: "Yes",
    }, 
    {
        name: `Verac the Defiled`,
        level: 115,
        health: 100,
        attack: ["Melee"],
        region: "Morytania",
        release: 2005,
        hasPet: "No",
    }, 
    {
        name: `Vet'ion`,
        level: 454,
        health: 150,
        attack: ["Magic", "Melee"],
        region: "Wilderness",
        release: 2014,
        hasPet: "Yes",
    }, 
    {
        name: `Vorkath`,
        level: 732,
        health: 750,
        attack: ["Dragonfire", "Magic", "Melee", "Ranged"],
        region: "Fremennik Province",
        release: 2018,
        hasPet: "Yes",
        image: 'https://oldschool.runescape.wiki/images/Vorkath.png?1ce3f'
    }, 
    {
        name: `The Whisperer`,
        level: 791,
        health: 900,
        attack: ["Magic", "Melee", "Ranged"],
        region: "Asgarnia",
        release: 2023,
        hasPet: "Yes",
    }, 
    {
        name: "Zulrah",
        level: 725,
        health: 500,
        attack: ["Magic", "Melee", "Ranged"],
        region: "Tirannwn",
        release: 2015,
        hasPet: "Yes",
    }, 
]


// const placeHolder = [
//     {
//         name: ,
//         level: ,
//         health: ,
//         attack: ,
//         region: ,
//         release: ``,
//         hasPet: ,
//     }, 
// ]