//Still Need to add Sporadic, SLayer, Minigame, Skilling, and Raid bosses

export const bossList = [
    {
        name: `Ahrim the Blighted`,
        level: 98,
        health: 100,
        attack: "Magic",
        region: "Morytania",
        release: `5,9,2005`,
        hasPet: false,
    }, 
    {
        name: `Ahrim the Blighted`,
        level: 98,
        health: 100,
        attack: "Magic",
        region: "Morytania",
        release: `5,9,2005`,
        hasPet: false,
    }, 
    {
        name: `Karil the Tainted`,
        level: 98,
        health: 100,
        attack: "Ranged",
        region: "Morytania",
        release: `5,9,2005`,
        hasPet: false,
    }, 
    {
        name: `Dharok the Wretched`,
        level: 115,
        health: 100,
        attack: "Melee",
        region: "Morytania",
        release: `5,9,2005`,
        hasPet: false,
    }, 
    {
        name: `Guthan the Infested`,
        level: 115,
        health: 100,
        attack: "Melee",
        region: "Morytania",
        release: `5,9,2005`,
        hasPet: false,
    }, 
    {
        name: `Torag the Corrupted`,
        level: 115,
        health: 100,
        attack: "Melee",
        region: "Morytania",
        release: `5,9,2005`,
        hasPet: false,
    }, 
    {
        name: `Verac the Defiled`,
        level: 115,
        health: 100,
        attack: "Melee",
        region: "Morytania",
        release: `5,9,2005`,
        hasPet: false,
    }, 
    {
        name: `Scurrius`,
        level: 200,
        health: 500,
        attack: "Magic/Melee/Ranged",
        region: "Misthalin",
        release: `01,24,2024`,
        hasPet: true,
    },
    {
        name: `Chaos Fanatic`,
        level: 202,
        health: 225,
        attack: "Magic",
        region: "Wilderness",
        release: `03,13,2014`,
        hasPet: true,
    }, 
    {
        name: `Crazy Archaeologist`,
        level: 204,
        health: 225,
        attack: "Melee/Ranged",
        region: "Wilderness",
        release: `03,13,2014`,
        hasPet: false,
    }, 
    {
        name: `Scorpia`,
        level: 225,
        health: 200,
        attack: 'Melee',
        region: 'Wilderness',
        release: `03,13,2014`,
        hasPet: true,
    }, 
    {
        name: `Giant Mole`,
        level: 230,
        health: 200,
        attack: "Melee",
        region: "Asgarnia",
        release: `03, 07, 2006`,
        hasPet: true,
    },
    {
        name: `Calvar'ion`,
        level: 264,
        health: 150,
        attack: "Melee",
        region: "Wilderness",
        release: `01,25,2023`,
        hasPet: true,
    }, 
    {
        name: `Deranged Archaeologist`,
        level: 276,
        health: 200,
        attack: "Melee/Ranged",
        region: "Misthalin",
        release: `09,07,2017`,
        hasPet: false,
    },
    {
        name: `King Black Dragon`,
        level: 276,
        health: 240,
        attack: "Melee/Dragonfire",
        region: "Wilderness",
        release: `09,24,2002`,
        hasPet: true,
    }, 
    {
        name: `Spindel`,
        level: 302,
        health: 515,
        attack: "Magic/Melee/Ranged",
        region: "Wilderness",
        release: `01,25,2023`,
        hasPet: true,
    }, 
    {
        name: `Dagannoth Supreme`,
        level: 303,
        health: 255,
        attack: "Ranged",
        region: "Fremennik Province",
        release: `11,07,2005`,
        hasPet: true,
    },
    {
        name: `Dagannoth Rex`,
        level: 303,
        health: 255,
        attack: "Melee",
        region: "Fremennik Province",
        release: `11,07,2005`,
        hasPet: true,
    },
    {
        name: `Dagannoth Prime`,
        level: 303,
        health: 255,
        attack: "Magic",
        region: "Fremennik Province",
        release: `11,07,2005`,
        hasPet: true,
    },
    {
        name: `Chaos Elemental`,
        level: 305,
        health: 250,
        attack: "Magic/Melee/Ranged",
        region: "Wilderness",
        release: `02,20,2006`,
        hasPet: true,
    }, 
    {
        name: `Sarachnis`,
        level: 318,
        health: 400,
        attack: "Melee/Ranged",
        region: "Kourend",
        release: `07,04,2019`,
        hasPet: true,
    },
    {
        name: `Artio`,
        level: 320,
        health: 450,
        attack: "Magic/Melee/Ranged",
        region: "Wilderness",
        release: `01,25,2023`,
        hasPet: true,
    }, 
    {
        name: `Blood Moon`,
        level: 329,
        health: 500,
        attack: "Melee",
        region: "Varlamore",
        release: `03,20,2024`,
        hasPet: false,
    },
    {
        name: `Blue Moon`,
        level: 329,
        health: 500,
        attack: "Melee",
        region: "Varlamore",
        release: `03,20,2024`,
        hasPet: false,
    },
    {
        name: `Eclipse Moon`,
        level: 329,
        health: 500,
        attack: "Melee",
        region: "Varlamore",
        release: `03,20,2024`,
        hasPet: false,
    },
    {
        name: "Kalphite Queen",
        level: 333,
        health: 510,
        attack: "Magic/Melee/Ranged",
        region: "Kharidian Desert",
        release: `09,07,2004`,
        hasPet: true,
    }, 
    {
        name: `Revenant Maledictus`,
        level: 397,
        health: 1250,
        attack: "Magic/Ranged",
        region: "Wilderness",
        release: `02,02,2022`,
        hasPet: false,
    }, 
    {
        name: `Vet'ion`,
        level: 454,
        health: 150,
        attack: "Magic/Melee",
        region: "Wilderness",
        release: `03,13,2014`,
        hasPet: true,
    }, 
    {
        name: `Venenatis`,
        level: 464,
        health: 850,
        attack: "Magic/Melee/Ranged",
        region: "Wilderness",
        release: `03,13,2014`,
        hasPet: true,
    }, 
    {
        name: `Calisto`,
        level: 470,
        health: 1000,
        attack: "Magic/Melee/Ranged",
        region: "Wilderness",
        release: `03,13,2014`,
        hasPet: true,
    }, 
    {
        name: "Kree'arra",
        level: 580,
        health: 255,
        attack: "Mage/Range/Melee",
        region: "Asgarnia",
        release: `10,17,2013`,
        hasPet: true,
    },
    {
        name: "Commander Zilyana",
        level: 596,
        health: 255,
        attack: "Magic/Melee",
        region: "Asgarnia",
        release: `10,17,2013`,
        hasPet: true,
    },
    {
        name: "General Graardor",
        level: 624,
        health: 255,
        attack: "Melee/Ranged",
        region: "Asgarnia",
        release: `10,17,2013`,
        hasPet: true,
    },
    {
        name: "K'ril Tsutsaroth",
        level: 650,
        health: 255,
        attack: "Magic/Melee",
        region: "Asgarnia",
        release: `10,17,2013`,
        hasPet: true,
    },
    {
        name: "Zulrah",
        level: 725,
        health: 500,
        attack: "Magic/Melee/Ranged",
        region: "Tirannwn",
        release: `01,08,2015`,
        hasPet: true,
    }, 
    {
        name: `Vorkath`,
        level: 732,
        health: 750,
        attack: "Dragonfire/Magic/Melee/Ranged",
        region: "Fremenik Province",
        release: `01,04,2018`,
        hasPet: true,
    }, 
    {
        name: `Phantom Muspah`,
        level: 741,
        health: 850,
        attack: "Magic/Melee/Ranged",
        region: "Fremenik Province",
        release: `01,11,2023`,
        hasPet: true,
    }, 
    {
        name: `Duke Sucellus`,
        level: 768,
        health: 440,
        attack: "Magic/Melee",
        region: "Fremenik Province",
        release: `07,27,2023`,
        hasPet: true,
    }, 
    {
        name: `Vardorvis`,
        level: 784,
        health: 700,
        attack: "Melee",
        region: "Kourend",
        release: `07,27,2023`,
        hasPet: true,
    }, 
    {
        name: `Corporeal Beast`,
        level: 785,
        health: 2000,
        attack: "Magic/Melee",
        region: "Wilderness",
        release: `11,16,2014`,
        hasPet: true,
    }, 
    {
        name: `The Whisperer`,
        level: 791,
        health: 900,
        attack: "Magic/Melee/Ranged",
        region: "Asgarnia",
        release: `07,27,2023`,
        hasPet: true,
    }, 
    {
        name: `The Leviathan`,
        level: 798,
        health: 900,
        attack: "Magic/Melee/Ranged",
        region: "Kharidian Desert",
        release: `07,27,2023`,
        hasPet: true,
    }, 
    {
        name: `The Nightmare`,
        level: 841,
        health: 2400,
        attack: "Magic/Melee/Ranged",
        region: "Morytania",
        release: `02,06,2020`,
        hasPet: true,
    }, 
    {
        name: `Nex`,
        level: 1001,
        health: 3400,
        attack: "Magic/Melee/Ranged",
        region: "Asgarnia",
        release: `01,05, 20222`,
        hasPet: true,
    }, 
    {
        name: `Phosani's Nightmare`,
        level: 1024,
        health: 3200,
        attack: "Magic/Melee/Ranged",
        region: "Morytania",
        release: `06,30,2021`,
        hasPet: true,
    }, 
]


// const placeHolder = [
//     {
//         name: ,
//         level: ,
//         health: ,
//         attack: ,
//         region: ,
//         release: ``,
//         hasPet: ,
//     }, 
// ]