//Still Need to add Minigame, Skilling, and Raid bosses

export const options = [
    {
        name: `Abyssal Sire`,
        level: 350,
        health: 400,
        attack: ["Melee"],
        region: "Misthilan",
        release: 2015,
        hasPet: "Yes",
        image: `https://oldschool.runescape.wiki/images/Abyssal_Sire.png`,
    }, 
    {
        name: `Ahrim the Blighted`,
        level: 98,
        health: 100,
        attack: ["Magic"],
        region: "Morytania",
        release: 2005,
        hasPet: "No",
        image: "https://oldschool.runescape.wiki/images/thumb/Ahrim_the_Blighted.png/320px-Ahrim_the_Blighted.png?33092",
    },
    {
        name: `Alchemical Hydra`,
        level: 426,
        health: 1100,
        attack: ["Magic", "Ranged"],
        region: "Kourend",
        release: 2019,
        hasPet: "Yes",
        image: `https://oldschool.runescape.wiki/images/Alchemical_Hydra_(serpentine).png`,
    }, 
    {
        name: `Amoxliatl`,
        level: 263,
        health: 520,
        attack: ["Magic"],
        region: "Varlamore",
        release: 2024,
        hasPet: "Yes",
        image: `https://oldschool.runescape.wiki/images/Amoxliatl.png`,
    },
    {
        name: `Araxxor`,
        level: 890,
        health: 1020,
        attack: ["Magic", "Melee", "Ranged"],
        region: "Morytania",
        release: 2024,
        hasPet: "Yes",
        image: `https://oldschool.runescape.wiki/images/Araxxor.png`,
    },
    {
        name: `Artio`,
        level: 320,
        health: 450,
        attack: ["Magic", "Melee", "Ranged"],
        region: "Wilderness",
        release: 2023,
        hasPet: "Yes",
        image: "https://oldschool.runescape.wiki/images/Artio.png"
    }, 
    {
        name: `Blood Moon`,
        level: 329,
        health: 500,
        attack: ["Melee"],
        region: "Varlamore",
        release: 2024,
        hasPet: "No",
        image: `https://oldschool.runescape.wiki/images/Blood_Moon.png`
    },
    {
        name: `Blue Moon`,
        level: 329,
        health: 500,
        attack: ["Melee"],
        region: "Varlamore",
        release: 2024,
        hasPet: "No",
        image: `https://oldschool.runescape.wiki/images/Blue_Moon.png`
    },
    {
        name: 'Branda the Fire Queen',
        level: 350,
        health: 600,
        attack: ['Melee'],
        region: 'Asgarnia',
        release: 2025,
        hasPet: 'Yes',
        image: `https://oldschool.runescape.wiki/images/Branda_the_Fire_Queen.png`
    },
    {
        name: `Bryophyta`,
        level: 128,
        health: 115,
        attack: ["Magic", "Melee"],
        region: "Misthalin",
        release: 2018,
        hasPet: "No",
        image: `https://oldschool.runescape.wiki/images/Bryophyta.png`,
    }, 
    {
        name: `Callisto`,
        level: 470,
        health: 1000,
        attack: ["Magic", "Melee", "Ranged"],
        region: "Wilderness",
        release: 2014,
        hasPet: "Yes",
        image: `https://oldschool.runescape.wiki/images/Artio.png`
    }, 
    {
        name: `Calvar'ion`,
        level: 264,
        health: 150,
        attack: ["Melee"],
        region: "Wilderness",
        release: 2023,
        hasPet: "Yes",
        image: `https://oldschool.runescape.wiki/images/Calvar%27ion.png`
    }, 
    {
        name: `Cerberus`,
        level: 318,
        health: 600,
        attack: ["Magic", "Melee", "Ranged"],
        region: "Asgarnia",
        release: 2015,
        hasPet: "Yes",
        image: `https://oldschool.runescape.wiki/images/Cerberus.png`,
    }, 
    {
        name: `Chaos Elemental`,
        level: 305,
        health: 250,
        attack: ["Magic", "Melee", "Ranged"],
        region: "Wilderness",
        release: 2006,
        hasPet: "Yes",
        image: `https://oldschool.runescape.wiki/images/Chaos_Elemental.png`
    }, 
    {
        name: `Chaos Fanatic`,
        level: 202,
        health: 225,
        attack: ["Magic"],
        region: "Wilderness",
        release: 2014,
        hasPet: "Yes",
        image: `https://oldschool.runescape.wiki/images/Chaos_Fanatic.png`
    }, 
    {
        name: "Commander Zilyana",
        level: 596,
        health: 255,
        attack: ["Magic", "Melee"],
        region: "Asgarnia",
        release: 2013,
        hasPet: "Yes",
        image: `https://oldschool.runescape.wiki/images/Commander_Zilyana.png`
    },
    {
        name: `Corporeal Beast`,
        level: 785,
        health: 2000,
        attack: ["Magic", "Melee"],
        region: "Wilderness",
        release: 2014,
        hasPet: "Yes",
        image: `https://oldschool.runescape.wiki/images/Corporeal_Beast.png`
    }, 
    {
        name: `Corrupted Hunllef`,
        level: 864,
        health: 1000,
        attack: ["Magic", "Ranged"],
        region: "Tirannwn",
        release: 2019,
        hasPet: "Yes",
        image: `https://oldschool.runescape.wiki/images/Corrupted_Hunllef.png`,
    },
    {
        name: `Crazy Archaeologist`,
        level: 204,
        health: 225,
        attack: ["Melee", "Ranged"],
        region: "Wilderness",
        release: 2014,
        hasPet: "No",
        image: `https://oldschool.runescape.wiki/images/Crazy_archaeologist.png`
    }, 
    {
        name: `Crystalline Hunllef`,
        level: 674,
        health: 600,
        attack: ["Magic", "Ranged"],
        region: "Tirannwn",
        release: 2019,
        hasPet: "Yes",
        image: `https://oldschool.runescape.wiki/images/Crystalline_Hunllef.png`,
    },
    {
        name: `Dagannoth Prime`,
        level: 303,
        health: 255,
        attack: ["Magic"],
        region: "Fremennik Province",
        release: 2005,
        hasPet: "Yes",
        image: `https://oldschool.runescape.wiki/images/Dagannoth_Prime.png`
    },
    {
        name: `Dagannoth Rex`,
        level: 303,
        health: 255,
        attack: ["Melee"],
        region: "Fremennik Province",
        release: 2005,
        hasPet: "Yes",
        image: `https://oldschool.runescape.wiki/images/Dagannoth_Rex.png`,
    },
    {
        name: `Dagannoth Supreme`,
        level: 303,
        health: 255,
        attack: ["Ranged"],
        region: "Fremennik Province",
        release: 2005,
        hasPet: "Yes",
        image: `https://oldschool.runescape.wiki/images/Dagannoth_Supreme.png`,
    },
    {
        name: `Dawn`,
        level: 228,
        health: 450,
        attack: ["Melee", "Ranged"],
        region: "Morytania",
        release: 2017,
        hasPet: "Yes",
        image: `https://oldschool.runescape.wiki/images/Dawn.png`,
    }, 
    {
        name: `Deranged Archaeologist`,
        level: 276,
        health: 200,
        attack: ["Melee", "Ranged"],
        region: "Misthalin",
        release: 2017,
        hasPet: "No",
        image: `https://oldschool.runescape.wiki/images/Deranged_archaeologist.png`,
    },
    {
        name: `Dharok the Wretched`,
        level: 115,
        health: 100,
        attack: ["Melee"],
        region: "Morytania",
        release: 2005,
        hasPet: "No",
        image: `https://oldschool.runescape.wiki/images/Dharok_the_Wretched.png`,
    }, 
    {
        name: `Duke Sucellus`,
        level: 768,
        health: 440,
        attack: ["Magic", "Melee"],
        region: "Fremennik Province",
        release: 2023,
        hasPet: "Yes",
        image: `https://oldschool.runescape.wiki/images/Duke_Sucellus.png`,
    }, 
    {
        name: `Dusk`,
        level: 248,
        health: 450,
        attack: ["Melee", "Ranged"],
        region: "Morytania",
        release: 2017,
        hasPet: "Yes",
        image: `https://oldschool.runescape.wiki/images/Dusk.png`,
    }, 
    {
        name: `Eclipse Moon`,
        level: 329,
        health: 500,
        attack: ["Melee"],
        region: "Varlamore",
        release: 2024,
        hasPet: "No",
        image: `https://oldschool.runescape.wiki/images/Eclipse_Moon.png`,
    },
    {
        name: 'Eldric the Ice King',
        level: 350,
        health: 600,
        attack: ['Melee'],
        region: 'Asgarnia',
        release: 2025,
        hasPet: 'Yes',
        image: `https://oldschool.runescape.wiki/images/Eldric_the_Ice_King.png`
    },
    {
        name: "General Graardor",
        level: 624,
        health: 255,
        attack: ["Melee","Ranged"],
        region: "Asgarnia",
        release: 2013,
        hasPet: "Yes",
        image: `https://oldschool.runescape.wiki/images/General_Graardor.png`,
    },
    {
        name: `Giant Mole`,
        level: 230,
        health: 200,
        attack: ["Melee"],
        region: "Asgarnia",
        release: 2006,
        hasPet: "Yes",
        image: `https://oldschool.runescape.wiki/images/Giant_Mole.png`,
    },
    {
        name: `Guthan the Infested`,
        level: 115,
        health: 100,
        attack: ["Melee"],
        region: "Morytania",
        release: 2005,
        hasPet: "No",
        image: `https://oldschool.runescape.wiki/images/Guthan_the_Infested.png`,
    },
    {
        name: `The Hueycoatl`,
        level: 642,
        health: 2500,
        attack: ["Magic", "Melee", "Ranged"],
        region: "Varlamore",
        release: 2024,
        hasPet: "Yes",
        image: `https://oldschool.runescape.wiki/images/The_Hueycoatl.png`,
    },
    {
        name: `Hespori`,
        level: 284,
        health: 300,
        attack: ["Magic", "Ranged"],
        region: "Kourend",
        release: 2019,
        hasPet: "Yes",
        image: `https://oldschool.runescape.wiki/images/Hespori.png`,
    }, 
    {
        name: "Kalphite Queen",
        level: 333,
        health: 510,
        attack: ["Magic", "Melee", "Ranged"],
        region: "Kharidian Desert",
        release: 2004,
        hasPet: "Yes",
        image: `https://oldschool.runescape.wiki/images/Kalphite_Queen.png`,
    }, 
    {
        name: `Karil the Tainted`,
        level: 98,
        health: 100,
        attack: ["Ranged"],
        region: "Morytania",
        release: 2005,
        hasPet: "No",
        image: `https://oldschool.runescape.wiki/images/Karil_the_Tainted.png`,
    },
    {
        name: `King Black Dragon`,
        level: 276,
        health: 240,
        attack: ["Dragonfire", "Melee"],
        region: "Wilderness",
        release: 2002,
        hasPet: "Yes",
        image: `https://oldschool.runescape.wiki/images/King_Black_Dragon.png`,
    }, 
    {
        name: "K'ril Tsutsaroth",
        level: 650,
        health: 255,
        attack: ["Magic", "Melee"],
        region: "Asgarnia",
        release: 2013,
        hasPet: "Yes",
        image: `https://oldschool.runescape.wiki/images/K'ril_Tsutsaroth.png`,
    },
    {
        name: `Kraken`,
        level: 291,
        health: 255,
        attack: ["Magic"],
        region: "Kandarin",
        release: 2014,
        hasPet: "Yes",
        image: `https://oldschool.runescape.wiki/images/Kraken.png`,
    }, 
    {
        name: "Kree'arra",
        level: 580,
        health: 255,
        attack: ["Magic", "Melee", "Ranged"],
        region: "Asgarnia",
        release: 2013,
        hasPet: "Yes",
        image: `https://oldschool.runescape.wiki/images/Kree%27arra.png`,
    },
    {
        name: `The Leviathan`,
        level: 798,
        health: 900,
        attack: ["Magic", "Melee", "Ranged"],
        region: "Kharidian Desert",
        release: 2023,
        hasPet: "Yes",
        image: `https://oldschool.runescape.wiki/images/The_Leviathan.png`,
    }, 
    {
        name: `The Mimic`,
        level: 186,
        health: 230,
        attack: ["Magic", "Melee"],
        region: "Kourend",
        release: 2019,
        hasPet: "No",
        image: `https://oldschool.runescape.wiki/images/The_Mimic.png`,
    }, 
    {
        name: `Obor`,
        level: 106,
        health: 120,
        attack: ["Melee", "Ranged"],
        region: "Misthalin",
        release: 2016,
        hasPet: "No",
        image: `https://oldschool.runescape.wiki/images/Obor.png`,
    }, 
    {
        name: `Nex`,
        level: 1001,
        health: 3400,
        attack: ["Magic", "Melee", "Ranged"],
        region: "Asgarnia",
        release: 2022,
        hasPet: "Yes",
        image: `https://oldschool.runescape.wiki/images/Nex.png`,
    }, 
    {
        name: `The Nightmare`,
        level: 841,
        health: 2400,
        attack: ["Magic", "Melee", "Ranged"],
        region: "Morytania",
        release: 2020,
        hasPet: "Yes",
        image: `https://oldschool.runescape.wiki/images/The_Nightmare.png`,
    }, 
    {
        name: `Phantom Muspah`,
        level: 741,
        health: 850,
        attack: ["Magic", "Melee", "Ranged"],
        region: "Fremennik Province",
        release: 2023,
        hasPet: "Yes",
        image: `https://oldschool.runescape.wiki/images/Phantom_Muspah_(ranged).png`,
    }, 
    {
        name: `Phosani's Nightmare`,
        level: 1024,
        health: 3200,
        attack: ["Magic", "Melee", "Ranged"],
        region: "Morytania",
        release: 2021,
        hasPet: "Yes",
        image: `https://oldschool.runescape.wiki/images/The_Nightmare.png`,
    }, 
    {
        name: `Revenant Maledictus`,
        level: 397,
        health: 1250,
        attack: ["Magic", "Ranged"],
        region: "Wilderness",
        release: 2022,
        hasPet: "No",
        image: `https://oldschool.runescape.wiki/images/Revenant_maledictus.png`,
    }, 
    {
        name: `Sarachnis`,
        level: 318,
        health: 400,
        attack: ["Melee", "Ranged"],
        region: "Kourend",
        release: 2019,
        hasPet: "Yes",
        image: `https://oldschool.runescape.wiki/images/Sarachnis.png`,
    },
    {
        name: `Scorpia`,
        level: 225,
        health: 200,
        attack: ['Melee'],
        region: 'Wilderness',
        release: 2014,
        hasPet: "Yes",
        image: `https://oldschool.runescape.wiki/images/Scorpia.png`,
    }, 
    {
        name: `Scurrius`,
        level: 200,
        health: 500,
        attack: ["Magic", "Melee", "Ranged"],
        region: "Misthalin",
        release: 2024,
        hasPet: "Yes",
        image: `https://oldschool.runescape.wiki/images/Scurrius.png`,
    },
    {
        name: `Skotizo`,
        level: 321,
        health: 450,
        attack: ["Magic", "Melee"],
        region: "Kourend",
        release: 2016,
        hasPet: "Yes",
        image: `https://oldschool.runescape.wiki/images/Skotizo.png`,
    }, 
    {
        name: `Sol Heredit`,
        level: 1563,
        health: 1500,
        attack: ["Melee"],
        region: "Varlamore",
        release: 2024,
        hasPet: "Yes",
        image: `https://oldschool.runescape.wiki/images/Sol_Heredit.png`,
    }, 
    {
        name: `Spindel`,
        level: 302,
        health: 515,
        attack: ["Magic", "Melee", "Ranged"],
        region: "Wilderness",
        release: 2023,
        hasPet: "Yes",
        image: `https://oldschool.runescape.wiki/images/Spindel.png`,
    }, 
    {
        name: `Thermonuclear Smoke Devil`,
        level: 301,
        health: 240,
        attack: ["Ranged"],
        region: "Kandarin",
        release: 2014,
        hasPet: "Yes",
        image: `https://oldschool.runescape.wiki/images/Thermonuclear_smoke_devil.png`,
    }, 
    {
        name: `Torag the Corrupted`,
        level: 115,
        health: 100,
        attack: ["Melee"],
        region: "Morytania",
        release: 2005,
        hasPet: "No",
        image: `https://oldschool.runescape.wiki/images/Torag_the_Corrupted.png`,
    }, 
    {
        name: `TzTok-Jad`,
        level: 702,
        health: 250,
        attack: ["Magic", "Melee", "Ranged"],
        region: "Karamja",
        release: 2005,
        hasPet: "Yes",
        image: `https://oldschool.runescape.wiki/images/TzTok-Jad.png`,
    }, 
    {
        name: `TzKal-Zuk`,
        level: 1400,
        health: 1200,
        attack: ["Magic", "Ranged"],
        region: "Karamja",
        release: 2017,
        hasPet: "Yes",
        image: `https://oldschool.runescape.wiki/images/TzKal-Zuk.png`,
    }, 
    {
        name: `Vardorvis`,
        level: 784,
        health: 700,
        attack: ["Melee"],
        region: "Kourend",
        release: 2023,
        hasPet: "Yes",
        image: `https://oldschool.runescape.wiki/images/Vardorvis.png`,
    }, 
    {
        name: `Venenatis`,
        level: 464,
        health: 850,
        attack: ["Magic", "Melee", "Ranged"],
        region: "Wilderness",
        release: 2014,
        hasPet: "Yes",
        image: `https://oldschool.runescape.wiki/images/Venenatis.png`,
    }, 
    {
        name: `Verac the Defiled`,
        level: 115,
        health: 100,
        attack: ["Melee"],
        region: "Morytania",
        release: 2005,
        hasPet: "No",
        image: `https://oldschool.runescape.wiki/images/Verac_the_Defiled.png`,
    }, 
    {
        name: `Vet'ion`,
        level: 454,
        health: 150,
        attack: ["Magic", "Melee"],
        region: "Wilderness",
        release: 2014,
        hasPet: "Yes",
        image: `https://oldschool.runescape.wiki/images/Vet%27ion.png`,
    }, 
    {
        name: `Vorkath`,
        level: 732,
        health: 750,
        attack: ["Dragonfire", "Magic", "Melee", "Ranged"],
        region: "Fremennik Province",
        release: 2018,
        hasPet: "Yes",
        image: 'https://oldschool.runescape.wiki/images/Vorkath.png?'
    }, 
    {
        name: `The Whisperer`,
        level: 791,
        health: 900,
        attack: ["Magic", "Melee", "Ranged"],
        region: "Asgarnia",
        release: 2023,
        hasPet: "Yes",
        image: `https://oldschool.runescape.wiki/images/The_Whisperer.png`,
    }, 
    {
        name: 'Yama',
        level: 1238,
        health: 2500,
        attack: ["Magic", "Melee", "Ranged"],
        region: "Kourend",
        release: 2025,
        hasPet: "Yes",
        image: `https://oldschool.runescape.wiki/images/Yama.png`
    },
    {
        name: "Zulrah",
        level: 725,
        health: 500,
        attack: ["Magic", "Melee", "Ranged"],
        region: "Tirannwn",
        release: 2015,
        hasPet: "Yes",
        image: `https://oldschool.runescape.wiki/images/Zulrah_(serpentine).png`,
    }, 
]


// const placeHolder = [
//     {
//         name: ,
//         level: ,
//         health: ,
//         attack: ,
//         region: ,
//         release: ``,
//         hasPet: ,
//     }, 
// ]